netrc_path: "~/.netrc"
netrc_owner: "{{ ansible_user | default(ansible_facts['user_id']) }}"
netrc_group: "{{ ansible_user | default(ansible_facts['user_id']) }}"
netrc_mode: "0600"

netrc_entries: []
