---

- name: Clone reverse-proxy git
  ansible.builtin.git:
    repo: "http://192.168.200.21:3000/maximilian/reverse-proxy.git"
    dest: {{ reverse_proxy_repo_dir }}
    version: main
    accept_hostkey: true
    clone: true
    update: true

- name: Create .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ reverse_proxy_repo_dir }}/.env"
    mode: '0644'

- name: Create and start reverse-proxy services
  community.docker.docker_compose_v2:
    project_src: {{ reverse_proxy_repo_dir }}
    pull: always
    remove_orphans: true
    state: present
