---

- name: Clone forgejo git
  ansible.builtin.git:
    repo: "http://192.168.200.21:3000/maximilian/forgejo.git"
    dest: "{{ forgejo_repo_dir }}"
    version: main
    accept_hostkey: true
    clone: true
    update: true

- name: Create and start forgejo services
  community.docker.docker_compose_v2:
    project_src: "{{ forgejo_repo_dir }}"
    pull: always
    remove_orphans: true
    state: present
