- name: Ensure .netrc file is created
  ansible.builtin.template:
    src: netrc.j2
    dest: "{{ netrc_path }}"
    owner: "{{ netrc_owner }}"
    group: "{{ netrc_group }}"
    mode: "{{ netrc_mode }}"
  no_log: true
