- name: Validate given data
  ansible.builtin.import_tasks: validate.yml
- name: Create .netrc files
  ansible.builtin.import_tasks: render.yml
- name: Ensure the file permissions are correct
  ansible.builtin.import_tasks: verify.yml
